spring.application.name=diploma

spring.datasource.url=jdbc:postgresql://localhost:5432/diploma_db
spring.datasource.username=michael
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update


